[package]
name = "parity-db"
version = "0.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Parity key-value database"

[dependencies]
log = "0.4.8"
parking_lot = "0.10"
memmap = "0.7"
blake2-rfc = "0.2.18"

[profile.release]
panic = 'abort'
codegen-units = 1
lto = "fat"
debug = true

[workspace]
members = [
	".",
	"bench/core",
	"bench/bin",
]

